[package]
name = "migrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
sqlx = { version = "0.6.3", features = ["postgres", "runtime-tokio-rustls", "time"] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
